# Generated by Django 4.0.3 on 2022-03-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='name of photo ', max_length=500)),
                ('description', models.CharField(default='description photo ', max_length=500)),
                ('date_pub', models.DateTimeField()),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('activate', models.BooleanField(default=True)),
                ('pos_x', models.DecimalField(decimal_places=3, max_digits=4)),
                ('pos_y', models.DecimalField(decimal_places=3, max_digits=4)),
                ('width', models.DecimalField(decimal_places=3, max_digits=4)),
                ('heigh', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
