# Generated by Django 4.0.3 on 2022-03-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_pub',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='heigh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pos_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pos_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
