# Generated by Django 4.0.3 on 2022-03-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesApp', '0002_alter_gallery_date_pub_alter_gallery_heigh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date_pub',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
