# Generated by Django 4.0.3 on 2022-03-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesApp', '0003_alter_gallery_date_pub_alter_gallery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.FileField(upload_to='photos/%y/%m/%d'),
        ),
    ]
