# Generated by Django 4.0.3 on 2022-03-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesApp', '0004_alter_gallery_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photo_3D',
            field=models.FileField(default='.glb', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
    ]
